[package]
name = "tasks"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", default-features = false, features = ["alloc", "std", "clock", "serde"] }
directories = "6.0.0"
ratatui = "0.29.0"
ron = "0.10.1"
serde = { version = "1.0.219", features = ["derive"] }
